baseURL = "/"
languageCode = "en-gb"
title = "Cognitive Bias Index"
enableRobotsTXT = true
disableAliases = true

[params]
  disallow_search_engines = false # set robots.txt to disallow everything
  description = "A tool for identifying and mitagating the systematic errors in thinking that affect the decisions and judgments that humans make."
  images = ["/images/social.png"]
  mixpanel_token = "484c55b83a2511e2108830b62471e515"

# add redirects/headers
[outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

# Configure Markup
[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Tools"
  url = "/tools/"
  weight = 1
